concurrent: 80
check-interval: 120
timeout: 5000
min-speed: 1024
download-timeout: 10
speed-test-url: https://fast.com
save-method: local
github-gist-id: ''
github-token: ''
github-api-mirror: ''
worker-url: https://example.worker.dev
worker-token: 1234567890
webdav-username: admin
webdav-password: admin
webdav-url: https://example.com/dav/
enable-web-ui: true
listen-port: 127.0.0.1:8199
old-api-key: admin
api-key: ef6be9d3f1d7f2cf19f1e7ae89c0d67f
sub-store-port: :8299
githubproxy: è‡ªåŠ¨é€‰æ‹©
github-proxy: https://git.anye.in/
sub-urls:
  - http://127.0.0.1:8199/all.yaml
  - https://raw.githubusercontent.com/snakem982/proxypool/main/source/v2ray-2.txt
  - https://gh-proxy.com/https://github.com/tonygyf/v2rayfree/blob/main/v2
  - https://gh-proxy.com/https://github.com/tonygyf/AutoMergePublicNodes/blob/master/list.txt
  - https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/splitted/mixed
  - https://gh-proxy.com/https://github.com/tonygyf/v2ray/blob/main/v.txt
  - https://raw.githubusercontent.com/shaoyouvip/free/refs/heads/main/base64.txt
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://gh-proxy.org/https://github.com/free18/v2ray/blob/main/v.txt
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://raw.githubusercontent.com/free-nodes/v2rayfree/main/v2
mihomo-overwrite-url: http://127.0.0.1:8199/bdg.yaml
rename-node: true
media-check: true
keep-success-proxies: false
print-progress: false
sub-urls-retry: 3
subscheck-version: v1.4.0
gui-auto: false
success-limit: 1000

# èŠ‚ç‚¹å‰ç¼€ï¼Œä¾èµ–rename-nodeä¸ºtrueæ‰ç”Ÿæ•ˆ
node-prefix: "@github tonygyf"

# å¡«å†™æ­å»ºçš„apprise API server åœ°å€
# https://notify.xxxx.us.kg/notify
apprise-api-server: ""
# å¡«å†™é€šçŸ¥ç›®æ ‡
# æ”¯æŒ100+ ä¸ªé€šçŸ¥æ¸ é“ï¼Œè¯¦ç»†æ ¼å¼è¯·å‚ç…§ https://github.com/caronc/apprise
recipient-url: 
  # telegramæ ¼å¼ï¼štgram://<bot_token>/<chat_id>
  # - tgram://xxxxxx/-1002149239223
  # é’‰é’‰æ ¼å¼ï¼šdingtalk://<secret>@<dd_token>/<chat_id>
  # - dingtalk://xxxxxx@xxxxxxx/123123
# è‡ªå®šä¹‰é€šçŸ¥æ ‡é¢˜
notify-title: "ğŸ”” èŠ‚ç‚¹çŠ¶æ€æ›´æ–°"