concurrent: 80
check-interval: 120
timeout: 3000
min-speed: 1024
download-timeout: 10
speed-test-url: https://fast.com/
save-method: local
github-gist-id: ''
github-token: ''
github-api-mirror: ''
worker-url: https://example.worker.dev
worker-token: 1234567890
webdav-username: admin
webdav-password: admin
webdav-url: https://example.com/dav/
enable-web-ui: true
listen-port: 127.0.0.1:8199
old-api-key: admin
api-key: ef6be9d3f1d7f2cf19f1e7ae89c0d67f
sub-store-port: :8299
githubproxy: 自动选择
github-proxy: https://github.lao.plus/
sub-urls:
  - http://127.0.0.1:8199/all.yaml
  - https://raw.githubusercontent.com/snakem982/proxypool/main/source/v2ray-2.txt
  - https://hk.gh-proxy.com/https://github.com/SoliSpirit/v2ray-configs/blob/main/Subscriptions/Sub10.txt
  - https://gh-proxy.com/https://github.com/tonygyf/v2rayfree/blob/main/v2
  - https://gh-proxy.com/https://github.com/tonygyf/AutoMergePublicNodes/blob/master/list.txt
  - https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/splitted/mixed
  - https://gh-proxy.com/https://github.com/tonygyf/v2ray/blob/main/v.txt
  - https://d.zrfme.com/vless-base64
mihomo-overwrite-url: http://127.0.0.1:8199/bdg.yaml
rename-node: true
media-check: true
keep-success-proxies: false
print-progress: false
sub-urls-retry: 3
subscheck-version: v1.4.0
gui-auto: false
success-limit: 1000
